"""evidence table

Revision ID: 1741e282ee1d
Revises: ce1b03e7b6f7
Create Date: 2026-09-30 09:18:53.390005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1741e282ee1d'
down_revision: Union[str, Sequence[str], None] = 'ce1b03e7b6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('claim', sa.String(), nullable=False),
    sa.Column('cycle', sa.String(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('quote_hash', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('page_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gone_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extractor', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professor_id', 'kind', 'source_url', 'quote_hash')
    )
    op.add_column('professors', sa.Column('recruiting_confidence', sa.String(), nullable=True))
    op.add_column('source_pages', sa.Column('page_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_pages', 'page_updated_at')
    op.drop_column('professors', 'recruiting_confidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
