"""application assessment fields

Revision ID: 33f45d75de9f
Revises: 01b3e5ce5a65
Create Date: 2026-10-01 20:44:48.302952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f45d75de9f'
down_revision: Union[str, Sequence[str], None] = '01b3e5ce5a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('fit_score', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('tier', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('gaps', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('decision', sa.String(), server_default='undecided', nullable=False))
    op.add_column('applications', sa.Column('assessment_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'assessment_by')
    op.drop_column('applications', 'decision')
    op.drop_column('applications', 'gaps')
    op.drop_column('applications', 'reason')
    op.drop_column('applications', 'tier')
    op.drop_column('applications', 'fit_score')
    # ### end Alembic commands ###
