"""analysis provenance

Revision ID: e660acb14f41
Revises: 33f45d75de9f
Create Date: 2026-10-02 14:32:59.646705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e660acb14f41'
down_revision: Union[str, Sequence[str], None] = '33f45d75de9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection_points', sa.Column('analyzed_by', sa.String(), nullable=True))
    op.add_column('papers', sa.Column('summary_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'summary_by')
    op.drop_column('connection_points', 'analyzed_by')
    # ### end Alembic commands ###
