"""professor pinned flag

Revision ID: f65050807453
Revises: e660acb14f41
Create Date: 2026-10-02 14:56:15.522440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65050807453'
down_revision: Union[str, Sequence[str], None] = 'e660acb14f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professors', sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False))
    # Carry over existing pins: everyone at "Pinned" or a later stage.
    op.execute("UPDATE professors SET pinned = true WHERE status IN ('shortlisted', 'analyzed', 'drafted', 'contacted', 'replied')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professors', 'pinned')
    # ### end Alembic commands ###
